name: Test Telegram
on: { workflow_dispatch: {} }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message
        run: |
          set -e
          echo "Sending Telegram test…"
          curl -s "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
            --get --data-urlencode "chat_id=${TELEGRAM_CHAT_ID}" \
            --data-urlencode "text=✅ Telegram wiring OK! (from GitHub Actions)"
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID:   ${{ secrets.TELEGRAM_CHAT_ID }}
